---
# tasks file for My-PC
########################
#         UPDATES      #
########################

- name: Debian Like | Update Cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Debian Like | Update System
  apt: name="*" state=latest
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
########################
# Instalacao de Pacotes#
########################
- name: Debian Like | Install common packages
  apt: 
    name: '{{ common_packages_debian }}' 
    install_recommends: yes
    state: latest
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  #####################
- name: Install Terminator
  apt:
    name: terminator
    state: present
#######################
# Configurando o Shell#
#######################
- name: Check if Oh-My-Zsh is installed
  stat:
    path: "{{ user_home }}/.oh-my-zsh"
  register: ohmyzsh
  become_user: "{{ ansible_user_id }}"

- block:
  - name: Install Oh-My-Zsh
    ansible.builtin.get_url:
      url: "{{ oh_my_zsh_install_script }}"
      dest: "/tmp/install_oh_my_zsh.sh"
      mode: '0755'

  - name: Remove existing Oh-My-Zsh installation
    ansible.builtin.file:
      path: "{{ user_home }}/.oh-my-zsh"
      state: absent
    when: ohmyzsh.stat.exists
    become_user: "{{ ansible_user_id }}"

  - name: Change default shell to ZSH
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh
    when: ansible_facts['distribution'] in ["Debian", "Ubuntu"] # Exemplo de verificação do SO

  - name: Remove installation script
    ansible.builtin.file:
      path: "/tmp/install_oh_my_zsh.sh"
      state: absent

  when: ohmyzsh.stat.exists == false

- name: Set ZSH theme to Agnoster
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.zshrc"
    regexp: '^ZSH_THEME=".*"'
    line: "ZSH_THEME=\"{{ zsh_theme }}\""
    create: yes
  become_user: "{{ ansible_user_id }}"

- name: Create ZSH completion directory
  ansible.builtin.file:
    path: "{{ user_home }}/.oh-my-zsh/completions"
    state: directory
    mode: '0755'
  become_user: "{{ ansible_user_id }}"

- name: Add autoload to compinit in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.zshrc"
    line: 'autoload -U compinit && compinit'
    insertafter: EOF
  become_user: "{{ ansible_user_id }}"
#######################################################

- name: Installing AWS CLI via pip3
  become: true
  pip:
    name: awscli
    executable: pip3

#######################################################
- name: Install Google Signing Key
  apt_key:
    url: 'https://dl.google.com/linux/linux_signing_key.pub'
    state: present

- name: Add Google Chrome Repository
  apt_repository:
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    state: present
    filename: google-chrome

- name: Install Google Chrome (Latest Version)
  apt:
    name: google-chrome-stable
    state: latest
#######################################################
########################
# Preparando Vagrant   #
########################
- name: Determinar a versão mais recente do Vagrant
  uri:
    url: https://releases.hashicorp.com/vagrant/index.json
    return_content: yes
  register: vagrant_releases
  become: false

- name: Definir a variável da versão mais recente do Vagrant
  set_fact:
    latest_vagrant_version: "{{ vagrant_releases.json.versions.keys() | max }}"

- name: Verificar se a versão mais recente do Vagrant está instalada
  command: "{{ vagrant_install_path }}/vagrant --version"
  register: vagrant_installed
  ignore_errors: true

- name: Analisar a versão instalada do Vagrant
  set_fact:
    installed_vagrant_version: "{{ vagrant_installed.stdout | regex_search('Vagrant (\\d+\\.\\d+\\.\\d+)', '\\1') | first }}"
  when: vagrant_installed.stdout is defined

- name: Baixar a versão mais recente do Vagrant
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ latest_vagrant_version }}/vagrant_{{ latest_vagrant_version }}_linux_amd64.zip"
    dest: "/tmp/vagrant_latest.zip"
    mode: '0755'
  when: latest_vagrant_version != installed_vagrant_version

- name: Extrair a versão mais recente do Vagrant
  unarchive:
    src: "/tmp/vagrant_latest.zip"
    dest: "{{ vagrant_install_path }}"
    remote_src: yes
  when: latest_vagrant_version != installed_vagrant_version

- name: Remover arquivo zip do Vagrant baixado
  file:
    path: "/tmp/vagrant_latest.zip"
    state: absent
  when: latest_vagrant_version != installed_vagrant_version

# Adicione tarefas adicionais se necessário para passos de instalação, como adicionar o Vagrant ao PATH

########################
# Preparando Terraform #
########################
- name: Determinar a versão mais recente do Terraform
  uri:
    url: https://releases.hashicorp.com/terraform/index.json
    return_content: yes
  register: terraform_releases
  become: false

- name: Definir a variável da versão mais recente do Terraform
  set_fact:
    latest_terraform_version: "{{ terraform_releases.json.versions.keys() | max }}"

- name: Verificar se a versão mais recente do Terraform está instalada
  command: "{{ terraform_install_path }}/terraform version"
  register: terraform_installed
  ignore_errors: true

- name: Definir a variável da versão instalada do Terraform como vazia
  set_fact:
    installed_terraform_version: ""
  when: terraform_installed is skipped or terraform_installed.rc != 0

- name: Analisar a versão instalada do Terraform
  set_fact:
    installed_terraform_version: "{{ terraform_installed.stdout | regex_search('Terraform v(\\d+\\.\\d+\\.\\d+)', '\\1') | first }}"
  when: terraform_installed.stdout is defined and terraform_installed.rc == 0

- name: Baixar a versão mais recente do Terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ latest_terraform_version }}/terraform_{{ latest_terraform_version }}_linux_amd64.zip"
    dest: "/tmp/terraform_latest.zip"
    mode: '0755'
  when: latest_terraform_version != installed_terraform_version

- name: Extrair a versão mais recente do Terraform
  unarchive:
    src: "/tmp/terraform_latest.zip"
    dest: "{{ terraform_install_path }}"
    remote_src: yes
    creates: "{{ terraform_install_path }}/terraform"
  when: latest_terraform_version != installed_terraform_version

- name: Remover arquivo zip do Terraform baixado
  file:
    path: "/tmp/terraform_latest.zip"
    state: absent
  when: latest_terraform_version != installed_terraform_version

- name: Verificar instalação do Terraform
  command: "{{ terraform_install_path }}/terraform version"
  register: terraform_version_output
  ignore_errors: true

- name: Exibir versão do Terraform
  debug:
    msg: "{{ terraform_version_output.stdout }}"
  when: terraform_version_output.stdout is defined

########################
#   FIM Terraform      #
########################

# Instalando Vault
- name: Installing Vault 1.8.1
  become: true
  unarchive:
    src: 'https://releases.hashicorp.com/vault/1.8.1/vault_1.8.1_linux_amd64.zip'
    dest: /usr/local/bin
    remote_src: yes

# Installing gomplate
- name: Installing gomplate 3.9.0
  become: true
  get_url:    
    url: 'https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64'
    dest: /usr/local/bin/gomplate
    mode: 755

# Install Google Cloud SDK
- name: Adicionar a chave do repositório do Google Cloud
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adicionar repositório do Google Cloud SDK
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main'
    state: present
    filename: 'google-cloud-sdk'

- name: Instalar o Google Cloud SDK
  apt:
    name: google-cloud-sdk
    #update_cache: yes
    state: latest
#####################    
# Instalar Microsoft #
#####################
- name: Instalar Chave da Microsoft
  become: true
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Instalar Repositório do VSCode
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    state: present
    filename: vscode
    update_cache: yes


- name: Instalar Visual Studio Code
  become: true
  apt:
    name: code
    state: present
    update_cache: yes
  ignore_errors: true

- name: Instalar Extensões do Visual Studio Code
  become: false
  shell:
    cmd: code --install-extension '{{ item }}'
  loop: 
    - ms-python.python
    - ms-azuretools.vscode-docker
    - bbenoist.vagrant
    - hashicorp.terraform
    - gruntfuggly.todo-tree
    - njpwerner.autodocstring
    - eamodio.gitlens
    - redhat.ansible
  ignore_errors: true

#######################
#   Install Docker    #
#######################
# Instalar chave GPG do Docker
- name: Instalar chave GPG do Docker (Ubuntu/Debian)
  apt_key:
    url: "{{ docker_gpg_key }}"
    state: present
  when: ansible_os_family == "Debian"

    # Adicionar repositório do Docker
- name: Instalar repositório do Docker (Ubuntu/Debian)
  apt_repository:
    repo: "{{ docker_repo_ubuntu }}"
    state: present
    filename: docker-ce
    #update_cache: yes
  when: ansible_os_family == "Debian"

    # Instalar Docker CE
- name: Instalar Docker CE (Ubuntu/Debian)
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

    # Adicionar o usuário atual ao grupo Docker
- name: Adicionar usuário atual ao grupo Docker
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

    # Instalar Docker-Compose
- name: Instalar Docker-Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "/usr/local/bin/docker-compose"
    mode: '0755'

    # Instalar conclusões de comando do Docker e Docker-Compose para Bash
- name: Instalar conclusões de comando do Docker e Docker-Compose para Bash (Ubuntu/Debian)
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { url: "https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash", dest: "/etc/bash_completion.d/docker-machine" }
    - { url: "https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose", dest: "/etc/bash_completion.d/docker-compose" }
  when: ansible_os_family == "Debian"

# Assegurar que o arquivo .zshrc exista para o usuário atual
- name: Garantir que o arquivo .zshrc exista para o usuário atual
  file:
    path: "/home/{{ ansible_user_id }}/.zshrc"
    state: touch
    mode: '0644'

# Adicionar plugins do Docker e Docker-Compose ao Zsh
- name: Adicionar plugins do Docker e Docker-Compose ao Zsh
  lineinfile:
    path: "/home/{{ ansible_user_id }}/.zshrc"
    regexp: '^\s*plugins=\((?!.*docker.*docker-compose.*)'
    line: 'plugins=(git docker docker-compose)'
    backrefs: yes
    insertafter: EOF
  when: ansible_shell_type == 'zsh'

###########################
#                         #
###########################
# Installing Kubectl
- name: Check if kubectl is installed
  command: "{{ kubectl_dest }} version --client=true"
  register: kubectl_installed
  ignore_errors: true

- name: Download kubectl
  get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ kubectl_dest }}"
    mode: '0755'
  when: kubectl_installed is failed

- name: Clone kubectx and kubens repository
  git:
    repo: "{{ kubectx_repo }}"
    dest: "{{ kubectx_dest }}"
    clone: yes
    update: yes

- name: Create symlinks for kubectx and kubens
  file:
    src: "{{ kubectx_dest }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - kubectx
    - kubens
  notify: Refresh Shell

- name: Ensure .zshrc exists for ZSH Completion
  file:
    path: "/home/{{ ansible_user_id }}/.zshrc"
    state: touch
    mode: '0644'

- name: Create symlinks for ZSH completions
  file:
    src: "{{ kubectx_dest }}/completion/{{ item }}"
    dest: "/home/{{ ansible_user_id }}/.oh-my-zsh/completions/_{{ item }}"
    state: link
  loop:
    - kubectx.zsh
    - kubens.zsh


    
# Install Golang 
- name: Adding Longsleep/Golang Backports Repository
  become: true
  apt_repository:
    repo: 'ppa:longsleep/golang-backports'

- name: Install Golang 
  become: true
  apt:
    name: golang-go
          
# OPTIONAL:
#  - PEEK - Lightweight Screen Recorder that can export as GIF
#  - OBS-STUDIO - Screen Recorder and Casting Software 
#  - Brave Browser - Secure web browser
#  - Ulauncher - Application Launcher

#  Adding Peek
- name: Adding Peek Repository
  become: true
  apt_repository:
    repo: 'ppa:peek-developers/stable'

- name: Install Peek
  become: true
  apt:
    name: peek
# Install obsproject 

- name: Install obsproject Ubuntu Repo
  become: true
  apt_repository:
    repo: 'ppa:obsproject/obs-studio'
- name: Install obs Studio
  become: true
  apt:
    name: obs-studi

# Install Brave
- name: Install Brave Key
  become: true
  apt_key:
    url: 'https://brave-browser-apt-release.s3.brave.com/brave-core.asc'
    state: present
- name: Install Brave Repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main'
    state: present
    filename: brave
- name: Install Brave Browser
  become: true
  apt:
    name: brave-browse

