---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:

    - name: Collect only selected facts
      ansible.builtin.setup:
        filter:
          - 'ansible_distribution'
          - 'ansible_machine_id'
          - 'ansible_*_mb'

...